# Generated by Django 4.2.7 on 2026-01-31 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emis_code', models.CharField(blank=True, help_text='EMIS code of the school this timetable belongs to', max_length=50, null=True)),
                ('grade', models.CharField(help_text='Grade/Class', max_length=50)),
                ('section', models.CharField(blank=True, help_text='Section (if applicable)', max_length=10)),
                ('subject', models.CharField(help_text='Subject being taught', max_length=200)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('period', models.CharField(choices=[('Period 1', 'Period 1'), ('Period 2', 'Period 2'), ('Period 3', 'Period 3'), ('Period 4', 'Period 4'), ('Period 5', 'Period 5'), ('Period 6', 'Period 6'), ('Period 7', 'Period 7'), ('Period 8', 'Period 8')], max_length=20)),
                ('room', models.CharField(blank=True, help_text='Room/Classroom', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['day', 'period', 'teacher'],
            },
        ),
        migrations.RemoveIndex(
            model_name='staff',
            name='school_staff_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='staff',
            name='school_staff_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='staff',
            name='school_staff_category_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='school_stud_emis_co_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='school_stud_grade_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='school_stud_section_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='school_stud_grade_section_idx',
        ),
        migrations.AddField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(help_text='Teacher assigned to this period', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='school.staff'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Principal user this timetable belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['teacher', 'day'], name='school_time_teacher_9b9e69_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['grade', 'section', 'day'], name='school_time_grade_169199_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('teacher', 'day', 'period')},
        ),
    ]
