# Generated by Django 4.2.7 on 2026-02-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_ensure_timetable_section_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='section',
            field=models.CharField(blank=True, help_text='Section (if applicable)', max_length=10),
        ),
    ]
