# Generated by Django 4.2.7 on 2026-04-10 15:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0058_tweak_subject_emojis'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='max_daily_teaching_periods',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Override max slots per day; null uses role default (5 for subject teachers).', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='max_weekly_teaching_periods',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Override weekly teaching slots; null uses role default (principal 2, VP 3, subject unlimited).', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='timetable_role',
            field=models.CharField(choices=[('subject_teacher', 'Subject teacher'), ('principal', 'Principal'), ('vice_principal', 'Vice principal'), ('other', 'Other')], default='subject_teacher', help_text='Used by timetable generator for weekly/daily teaching caps.', max_length=32),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='period',
            field=models.CharField(choices=[('Period 1', 'Period 1'), ('Period 2', 'Period 2'), ('Period 3', 'Period 3'), ('Period 4', 'Period 4'), ('Period 5', 'Period 5'), ('Period 6', 'Period 6'), ('Period 7', 'Period 7'), ('Period 8', 'Period 8'), ('Period 9', 'Period 9'), ('Period 10', 'Period 10')], max_length=20),
        ),
        migrations.CreateModel(
            name='TimetableSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_substitutions_marked', to=settings.AUTH_USER_MODEL)),
                ('substitute_teacher', models.ForeignKey(blank=True, help_text='Null means slot uncovered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_substitutions_covering', to='school.staff')),
                ('timetable_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='school.timetable')),
            ],
            options={
                'ordering': ['-date', 'timetable_entry_id'],
            },
        ),
        migrations.CreateModel(
            name='TimetableDayStaffStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('emis_code', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('leave', 'Leave'), ('on_duty', 'On duty')], default='present', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_day_statuses', to='school.staff')),
            ],
            options={
                'ordering': ['-date', 'staff__name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolTimetableDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emis_code', models.CharField(blank=True, max_length=50, null=True)),
                ('default_periods_per_day', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('working_days', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(6)])),
                ('lunch_break_minutes', models.PositiveSmallIntegerField(default=40)),
                ('lunch_after_period', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('short_break_minutes', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_timetable_defaults', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSectionTimetableConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emis_code', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.CharField(max_length=50)),
                ('section', models.CharField(blank=True, default='', max_length=10)),
                ('periods_per_day', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('extra_activity_label', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_section_timetable_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['grade', 'section'],
            },
        ),
        migrations.AddConstraint(
            model_name='timetablesubstitution',
            constraint=models.UniqueConstraint(fields=('date', 'timetable_entry'), name='timetable_substitution_date_entry_uniq'),
        ),
        migrations.AddConstraint(
            model_name='timetabledaystaffstatus',
            constraint=models.UniqueConstraint(fields=('date', 'staff'), name='timetable_day_staff_status_uniq'),
        ),
        migrations.AddConstraint(
            model_name='schooltimetabledefaults',
            constraint=models.UniqueConstraint(fields=('user',), name='school_timetable_defaults_user_uniq'),
        ),
        migrations.AddConstraint(
            model_name='classsectiontimetableconfig',
            constraint=models.UniqueConstraint(fields=('user', 'grade', 'section'), name='class_section_timetable_config_user_grade_section_uniq'),
        ),
    ]
