# Generated by Django — expands timetable working_days range to 1–7.

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0068_remove_student_school_stud_emis_active_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schooltimetabledefaults",
            name="working_days",
            field=models.PositiveSmallIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(7),
                ],
            ),
        ),
    ]
