# Generated by Django 4.2.7 on 2026-05-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0071_school_bell_google_calendar'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='timetablegooglecalendarevent',
            new_name='school_time_princip_a889d0_idx',
            old_name='school_timet_principal_2b0fbd_idx',
        ),
    ]
