/**
 * Export generated timetable to TXT, PDF, or DOCX.
 * Uses generatedResult from POST /api/school/timetable/generate/
 */

import { BREAK_AFTER_PERIOD } from './timetablePeriods';

function findEntryForClass(entries, classItem, periodKey, dayName) {
  return entries.find(
    (e) =>
      e.day === dayName &&
      e.period === periodKey &&
      e.grade === classItem.grade &&
      (e.section || '') === (classItem.section || '')
  );
}

function findEntryForTeacher(entries, teacherId, periodKey, dayName) {
  return entries.find((e) => {
    const tid = typeof e.teacher === 'object' ? e.teacher?.id : e.teacher;
    return e.day === dayName && String(tid) === String(teacherId) && e.period === periodKey;
  });
}

/**
 * Build the same `by_class` shape as the generator export, from the principal grid’s
 * current scope (day vs week, by class vs by teacher).
 */
export function buildLivePrincipalTimetableExport({
  viewBy,
  timeScope,
  masterDayParam,
  days,
  classRows,
  teacherRows,
  entries,
  periodsForClass,
  teacherPeriodsSlice,
  getTeacherName,
  labels = {},
}) {
  const dayList =
    timeScope === 'week'
      ? [...days]
      : masterDayParam && days.includes(masterDayParam)
        ? [masterDayParam]
        : [];

  const by_class = {};

  const slotsForDay = (periods, dayName, pickEntry) => {
    const slots = [];
    for (const period of periods) {
      if (period.key === BREAK_AFTER_PERIOD) {
        slots.push({ type: 'break', label: labels.break || 'Break' });
      }
      const entry = pickEntry(period.key, dayName);
      if (entry) {
        const tn = getTeacherName(entry);
        const slot = {
          type: 'class',
          label: period.key,
          subject: entry.subject || '-',
          teacher_name: tn || undefined,
        };
        if (viewBy === 'teacher') {
          const grade = entry.grade != null ? String(entry.grade).trim() : '';
          const sec = entry.section != null ? String(entry.section).trim() : '';
          const classLabel =
            grade || sec ? `${grade}${sec ? `-${sec}` : ''}` : undefined;
          if (classLabel) slot.class_label = classLabel;
        }
        slots.push(slot);
      }
    }
    return slots;
  };

  if (viewBy === 'class') {
    for (const c of classRows) {
      const label = `${c.grade}${c.section ? `-${c.section}` : ''}`;
      const periods = periodsForClass(c);
      by_class[label] = dayList.map((dayName) => ({
        day: dayName,
        slots: slotsForDay(periods, dayName, (pk, dn) => findEntryForClass(entries, c, pk, dn)),
      }));
    }
  } else {
    for (const t of teacherRows) {
      const label = t.name || `Teacher ${t.id}`;
      by_class[label] = dayList.map((dayName) => ({
        day: dayName,
        slots: slotsForDay(teacherPeriodsSlice, dayName, (pk, dn) =>
          findEntryForTeacher(entries, t.id, pk, dn)
        ),
      }));
    }
  }

  return { by_class };
}

/**
 * Build plain text representation of the timetable (by class).
 * @param {{ by_class: Record<string, Array<{ day: string, slots: Array<{ type: string, label: string, subject?: string, teacher_name?: string }> }> }} generatedResult
 * @returns {string}
 */
export function timetableToText(generatedResult, options = {}) {
  if (!generatedResult?.by_class) return '';
  const labels = {
    classPrefix: options.labels?.classPrefix || 'Class',
    breakLabel: options.labels?.breakLabel || 'Break',
    generatedOn: options.labels?.generatedOn || 'Generated on',
    generatedBy: options.labels?.generatedBy || 'Generated by',
  };
  const lines = [];
  if (options.metadata?.generatedBy) {
    lines.push(
      `${labels.generatedBy}: ${options.metadata.generatedBy} · ${labels.generatedOn}: ${new Date().toLocaleString()}`
    );
    lines.push('');
  }
  for (const [classKey, daySlots] of Object.entries(generatedResult.by_class)) {
    lines.push(`${labels.classPrefix} ${classKey}`);
    lines.push('');
    for (const { day, slots } of daySlots) {
      lines.push(`${day}:`);
      const parts = slots.map((slot) => {
        if (slot.type === 'break') return slot.label || labels.breakLabel;
        const cls = slot.class_label ? ` [${slot.class_label}]` : '';
        return `${slot.label}: ${slot.subject || '-'}${cls}${slot.teacher_name ? ` (${slot.teacher_name})` : ''}`;
      });
      lines.push(parts.join(', '));
      lines.push('');
    }
    lines.push('---');
    lines.push('');
  }
  return lines.join('\n').trim();
}

/**
 * Download timetable as TXT file.
 */
export function exportTimetableTxt(generatedResult, filename = 'timetable.txt', options = {}) {
  const text = timetableToText(generatedResult, options);
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/* ─── PDF palette constants ──────────────────────────────────────────────── */
const PDF_BRAND = [30, 58, 95];
const PDF_MUTED = [100, 116, 139];

// Per-subject colour themes (bg, fg text, accent bar)
const PDF_SUBJECT_PALETTES = [
  { keys: ['math'],                               bg:[238,243,255], fg:[45,58,140],  accent:[83,74,183]  },
  { keys: ['english','literature','lang'],         bg:[232,248,243], fg:[10,89,64],   accent:[15,110,86]  },
  { keys: ['science','bio','chem','phys'],         bg:[255,244,224], fg:[122,69,0],   accent:[186,117,23] },
  { keys: ['urdu','arabic'],                       bg:[254,243,231], fg:[107,53,0],   accent:[239,159,39] },
  { keys: ['social','history','geo','pak stud'],   bg:[250,236,231], fg:[122,45,18],  accent:[153,60,29]  },
  { keys: ['art','craft','draw','music'],          bg:[251,234,240], fg:[122,36,64],  accent:[153,53,86]  },
  { keys: ['pe','phys ed','sport','gym'],          bg:[234,243,222], fg:[46,92,10],   accent:[59,109,17]  },
  { keys: ['ict','comp','tech'],                   bg:[230,241,251], fg:[12,61,122],  accent:[24,95,165]  },
  { keys: ['islamic','quran','deen'],              bg:[232,248,243], fg:[10,89,64],   accent:[29,158,117] },
];

// Per-day header colours (cycles for as many days as there are)
const PDF_DAY_PALETTES = [
  { bg:[238,237,254], fg:[60,52,137]  },
  { bg:[225,245,238], fg:[8,80,65]    },
  { bg:[250,236,231], fg:[113,43,19]  },
  { bg:[251,234,240], fg:[114,36,62]  },
  { bg:[230,241,251], fg:[12,61,122]  },
  { bg:[240,253,244], fg:[22,101,52]  },
];

function pdfSubjectPalette(subject) {
  const s = (subject || '').toLowerCase();
  for (const p of PDF_SUBJECT_PALETTES) {
    if (p.keys.some(k => s.includes(k))) return p;
  }
  // deterministic fallback so the same subject always gets the same colour
  let hash = 0;
  for (let i = 0; i < s.length; i++) hash = (hash * 31 + s.charCodeAt(i)) & 0xffff;
  return PDF_SUBJECT_PALETTES[hash % PDF_SUBJECT_PALETTES.length];
}

/* ─── Drawing primitives ─────────────────────────────────────────────────── */

/** Coloured subject card: rounded bg + left accent pill + bold subject + italic subtitle (class or teacher). */
function pdfDrawSubjectCell(doc, x, y, w, h, subject, subtitle) {
  const p = pdfSubjectPalette(subject);
  const r = 2;

  // Background
  doc.setFillColor(...p.bg);
  doc.roundedRect(x, y, w, h, r, r, 'F');

  // Left accent pill (narrow rounded rect; its outer corners land within cell bg)
  doc.setFillColor(...p.accent);
  doc.roundedRect(x, y, 3, h, 1.5, 1.5, 'F');

  const tx = x + 5;
  const maxW = w - 7;
  const sub = subtitle && String(subtitle).trim();

  if (sub) {
    const midY = y + h / 2;
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...p.fg);
    const subjectLines = doc.splitTextToSize(subject || '-', maxW).slice(0, 2);
    doc.text(subjectLines, tx, midY - 2.5);

    const lighter = p.fg.map(c => Math.min(255, c + 75));
    doc.setFontSize(7);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(...lighter);
    doc.text(sub, tx, midY + 4, { maxWidth: maxW });
  } else {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...p.fg);
    const subjectLines = doc.splitTextToSize(subject || '-', maxW).slice(0, 2);
    doc.text(subjectLines, tx, y + h / 2, { maxWidth: maxW });
  }
}

/** Beige dashed-border break card */
function pdfDrawBreakCell(doc, x, y, w, h, breakLabel = 'Break') {
  doc.setFillColor(241, 239, 232);
  doc.roundedRect(x, y, w, h, 2, 2, 'F');
  doc.setDrawColor(180, 178, 169);
  doc.setLineWidth(0.3);
  doc.roundedRect(x, y, w, h, 2, 2, 'S');
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(95, 94, 90);
  doc.text(breakLabel, x + w / 2, y + h / 2 + 1.5, { align: 'center' });
}

/** Coloured day-header card */
function pdfDrawDayHeader(doc, x, y, w, h, dayName, palIdx) {
  const pal = PDF_DAY_PALETTES[palIdx % PDF_DAY_PALETTES.length];
  doc.setFillColor(...pal.bg);
  doc.roundedRect(x, y, w, h, 2.5, 2.5, 'F');
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...pal.fg);
  doc.text(dayName, x + w / 2, y + h / 2 + 2, { align: 'center' });
}

/** Slate period-number label card */
function pdfDrawPeriodLabel(doc, x, y, w, h, num) {
  doc.setFillColor(226, 232, 240);
  doc.roundedRect(x, y, w, h, 2, 2, 'F');
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text(String(num), x + w / 2, y + h / 2 + 2, { align: 'center' });
}

/** Empty slot placeholder */
function pdfDrawEmptyCell(doc, x, y, w, h) {
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(x, y, w, h, 2, 2, 'F');
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text('—', x + w / 2, y + h / 2 + 1.5, { align: 'center' });
}

/** jsPDF image format string from a data URL (`school_picture` from profile API). */
function jspdfFormatFromSchoolPictureDataUrl(dataUrl) {
  if (!dataUrl || typeof dataUrl !== 'string') return 'PNG';
  const m = dataUrl.match(/^data:image\/([^;,]+)/i);
  if (!m) return 'PNG';
  const sub = m[1].toLowerCase().trim();
  if (sub === 'jpeg' || sub === 'jpg') return 'JPEG';
  if (sub === 'png') return 'PNG';
  if (sub === 'webp') return 'WEBP';
  if (sub === 'gif') return 'GIF';
  return 'PNG';
}

/* ─── Main PDF export ────────────────────────────────────────────────────── */
/**
 * Download timetable as PDF.
 * A4 landscape, one page per class, custom-drawn card grid — no autoTable.
 *
 * @param {{ schoolLogoDataUrl?: string | null, timetableRowKind?: 'class'|'teacher' }} [options]
 */
export async function exportTimetablePdf(generatedResult, filename = 'timetable.pdf', options = {}) {
  if (!generatedResult?.by_class) return;

  const schoolLogoDataUrl = options.schoolLogoDataUrl ?? null;
  const logoFormat = jspdfFormatFromSchoolPictureDataUrl(schoolLogoDataUrl);
  const rowKind = options.timetableRowKind === 'teacher' ? 'teacher' : 'class';
  const labels = {
    classPrefix: options.labels?.classPrefix || 'Class',
    weeklyTimetable: options.labels?.weeklyTimetable || 'Weekly Timetable',
    periodWord: options.labels?.periodWord || 'Period',
    dayWord: options.labels?.dayWord || 'Day',
    breakLabel: options.labels?.breakLabel || 'Break',
    generatedOn: options.labels?.generatedOn || 'Generated on',
    generatedBy: options.labels?.generatedBy || 'Generated by',
  };
  const metadata = options.metadata || {};
  const mobileOptimized = Boolean(options.mobileOptimized && rowKind === 'teacher');

  const { jsPDF } = await import('jspdf');
  const doc  = new jsPDF({
    orientation: mobileOptimized ? 'portrait' : 'landscape',
    unit: 'mm',
    format: 'a4',
  });
  const pageW = doc.internal.pageSize.width;   // 297
  const pageH = doc.internal.pageSize.height;  // 210
  const MG  = 9;  // page margin
  const GAP = 1.5; // gap between cards

  const dateStr = new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' });

  const pages = [];
  for (const [classLabel, daySlots] of Object.entries(generatedResult.by_class)) {
    if (!mobileOptimized) {
      pages.push({ classLabel, daySlots });
      continue;
    }
    daySlots.forEach((dayRow) => {
      pages.push({ classLabel, daySlots: [dayRow] });
    });
  }

  for (const [idx, { classLabel, daySlots }] of pages.entries()) {
    if (idx > 0) doc.addPage();

    const days          = daySlots.map(d => d.day);
    const templateSlots = daySlots[0]?.slots ?? [];
    const numPeriods    = templateSlots.filter(s => s.type !== 'break').length;
    const numBreaks     = templateSlots.length - numPeriods;

    // Index each day's slots by label for O(1) lookup
    const byDayLabel = {};
    for (const { day, slots } of daySlots) {
      byDayLabel[day] = {};
      for (const s of slots) byDayLabel[day][s.label] = s;
    }

    /* ── Header banner ─────────────────────────────────────────────────── */
    const hdrY = MG;
    const hdrH = 23;

    doc.setFillColor(...PDF_BRAND);
    doc.roundedRect(MG, hdrY, pageW - MG * 2, hdrH, 3, 3, 'F');

    // School logo (uploaded in school / report-card profile — never app branding)
    if (schoolLogoDataUrl) {
      try {
        doc.addImage(schoolLogoDataUrl, logoFormat, MG + 4, hdrY + (hdrH - 15) / 2, 15, 15);
      } catch (_) {
        /* invalid or unsupported image — omit logo */
      }
    }

    // Title: class section vs teacher name
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(15);
    doc.setTextColor(255, 255, 255);
    doc.text(
      rowKind === 'teacher' ? classLabel : `${labels.classPrefix} ${classLabel}`,
      pageW / 2,
      hdrY + 10.5,
      { align: 'center' }
    );

    // Subtitle
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(160, 200, 235);
    doc.text(
      `${labels.weeklyTimetable}  ·  ${numPeriods} ${labels.periodWord}${numPeriods !== 1 ? 's' : ''}  ·  ${days.length} ${labels.dayWord}${days.length !== 1 ? 's' : ''}`,
      pageW / 2, hdrY + 18, { align: 'center' }
    );

    // Date — top-right inside banner
    doc.setFontSize(7);
    doc.text(dateStr, pageW - MG - 4, hdrY + 10.5, { align: 'right' });

    /* ── Grid dimensions ────────────────────────────────────────────────── */
    const gridY    = hdrY + hdrH + 4;
    const footerY  = pageH - MG;
    const gridH    = footerY - gridY - 6;  // 6 mm reserved for footer text

    const dayHdrH  = 11;
    const contentH = gridH - dayHdrH - GAP;

    // Breaks get 55 % of a period row height so they don't waste space
    const BREAK_RATIO  = 0.55;
    const totalUnits   = numPeriods + numBreaks * BREAK_RATIO;
    const periodRowH   = Math.max(11, contentH / (totalUnits || 1));
    const breakRowH    = periodRowH * BREAK_RATIO;

    const periodColW = 13;
    const usableW    = pageW - MG * 2;
    const dayColW    = (usableW - periodColW - GAP - GAP * (days.length - 1)) / Math.max(days.length, 1);

    /* ── Day headers ────────────────────────────────────────────────────── */
    for (let di = 0; di < days.length; di++) {
      const cx = MG + periodColW + GAP + di * (dayColW + GAP);
      pdfDrawDayHeader(doc, cx, gridY, dayColW, dayHdrH, days[di], di);
    }

    /* ── Period rows ────────────────────────────────────────────────────── */
    let curY = gridY + dayHdrH + GAP;
    let pNum = 0;

    for (const slot of templateSlots) {
      const rH = slot.type === 'break' ? breakRowH : periodRowH;

      if (slot.type === 'break') {
        // Period label column — muted tilde
        doc.setFillColor(235, 233, 226);
        doc.roundedRect(MG, curY, periodColW, rH, 2, 2, 'F');
        doc.setFontSize(8);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(130, 128, 120);
        doc.text('~', MG + periodColW / 2, curY + rH / 2 + 1.5, { align: 'center' });

        for (let di = 0; di < days.length; di++) {
          pdfDrawBreakCell(
            doc,
            MG + periodColW + GAP + di * (dayColW + GAP),
            curY,
            dayColW,
            rH,
            labels.breakLabel
          );
        }
      } else {
        pNum++;
        pdfDrawPeriodLabel(doc, MG, curY, periodColW, rH, pNum);

        for (let di = 0; di < days.length; di++) {
          const cx      = MG + periodColW + GAP + di * (dayColW + GAP);
          const dayData = byDayLabel[days[di]]?.[slot.label];

          if (!dayData || !dayData.subject) {
            pdfDrawEmptyCell(doc, cx, curY, dayColW, rH);
          } else {
            const cls = dayData.class_label != null ? String(dayData.class_label).trim() : '';
            const subtitle =
              rowKind === 'teacher'
                ? cls || dayData.teacher_name || ''
                : dayData.teacher_name || cls || '';
            pdfDrawSubjectCell(doc, cx, curY, dayColW, rH, dayData.subject, subtitle);
          }
        }
      }

      curY += rH + GAP;
    }

    /* ── Footer ─────────────────────────────────────────────────────────── */
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...PDF_MUTED);
    const generatedByText = metadata.generatedBy ? `  ·  ${labels.generatedBy}: ${metadata.generatedBy}` : '';
    doc.text(
      rowKind === 'teacher'
        ? `${classLabel}  ·  ${days.join(' – ')}  ·  ${labels.generatedOn}: ${dateStr}${generatedByText}`
        : `${labels.classPrefix} ${classLabel}  ·  ${days.join(' – ')}  ·  ${labels.generatedOn}: ${dateStr}${generatedByText}`,
      pageW / 2, pageH - MG, { align: 'center' }
    );
  }

  doc.save(filename);
}

/**
 * Download timetable as DOCX using docx.
 */
export async function exportTimetableDocx(generatedResult, filename = 'timetable.docx') {
  const { Document, Packer, Paragraph, TextRun, HeadingLevel } = await import('docx');
  const children = [];

  if (!generatedResult?.by_class) {
    return;
  }

  for (const [classKey, daySlots] of Object.entries(generatedResult.by_class)) {
    children.push(
      new Paragraph({
        text: `Class ${classKey}`,
        heading: HeadingLevel.HEADING_2,
        spacing: { after: 200 },
      })
    );
    for (const { day, slots } of daySlots) {
      const parts = slots.map(slot => {
        if (slot.type === 'break') return slot.label;
        const cls = slot.class_label ? ` [${slot.class_label}]` : '';
        return `${slot.label}: ${slot.subject || '-'}${cls}${slot.teacher_name ? ` (${slot.teacher_name})` : ''}`;
      });
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: day, bold: true }),
            new TextRun({ text: ` — ${parts.join(', ')}`, break: 1 }),
          ],
          spacing: { after: 120 },
        })
      );
    }
    children.push(
      new Paragraph({ text: '', spacing: { after: 200 } })
    );
  }

  const doc = new Document({
    sections: [{ children }],
  });

  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
